// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: environment.proto

package environmentService;

public interface CurrentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:environmentService.CurrentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string currentNew = 1;</code>
   */
  java.lang.String getCurrentNew();
  /**
   * <code>string currentNew = 1;</code>
   */
  com.google.protobuf.ByteString
      getCurrentNewBytes();
}
