// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: environment.proto

package environmentService;

public interface CurrentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:environmentService.CurrentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string current = 1;</code>
   */
  java.lang.String getCurrent();
  /**
   * <code>string current = 1;</code>
   */
  com.google.protobuf.ByteString
      getCurrentBytes();
}
