// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: environment.proto

package environmentService;

public interface CurrentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:environmentService.CurrentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 current = 1;</code>
   */
  int getCurrent();
}
