// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: environment.proto

package environmentService;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:environmentService.Empty)
    com.google.protobuf.MessageOrBuilder {
}
