# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: environment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='environment.proto',
  package='environmentService',
  syntax='proto3',
  serialized_options=b'\n\022environmentServiceB\026EnvironmentServiceImplP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x65nvironment.proto\x12\x12\x65nvironmentService\"\x1e\n\x0cTempResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\" \n\x0f\x43urrentResponse\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1c\n\x0bTempRequest\x12\r\n\x05value\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\xc0\x01\n\x12\x45nvironmentService\x12R\n\x0bsetRoomTemp\x12\x1f.environmentService.TempRequest\x1a .environmentService.TempResponse\"\x00\x12V\n\x12getCurrentRoomTemp\x12\x19.environmentService.Empty\x1a#.environmentService.CurrentResponse\"\x00\x42.\n\x12\x65nvironmentServiceB\x16\x45nvironmentServiceImplP\x01\x62\x06proto3'
)




_TEMPRESPONSE = _descriptor.Descriptor(
  name='TempResponse',
  full_name='environmentService.TempResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='environmentService.TempResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=71,
)


_CURRENTRESPONSE = _descriptor.Descriptor(
  name='CurrentResponse',
  full_name='environmentService.CurrentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='environmentService.CurrentResponse.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=105,
)


_TEMPREQUEST = _descriptor.Descriptor(
  name='TempRequest',
  full_name='environmentService.TempRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='environmentService.TempRequest.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=135,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='environmentService.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['TempResponse'] = _TEMPRESPONSE
DESCRIPTOR.message_types_by_name['CurrentResponse'] = _CURRENTRESPONSE
DESCRIPTOR.message_types_by_name['TempRequest'] = _TEMPREQUEST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TempResponse = _reflection.GeneratedProtocolMessageType('TempResponse', (_message.Message,), {
  'DESCRIPTOR' : _TEMPRESPONSE,
  '__module__' : 'environment_pb2'
  # @@protoc_insertion_point(class_scope:environmentService.TempResponse)
  })
_sym_db.RegisterMessage(TempResponse)

CurrentResponse = _reflection.GeneratedProtocolMessageType('CurrentResponse', (_message.Message,), {
  'DESCRIPTOR' : _CURRENTRESPONSE,
  '__module__' : 'environment_pb2'
  # @@protoc_insertion_point(class_scope:environmentService.CurrentResponse)
  })
_sym_db.RegisterMessage(CurrentResponse)

TempRequest = _reflection.GeneratedProtocolMessageType('TempRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEMPREQUEST,
  '__module__' : 'environment_pb2'
  # @@protoc_insertion_point(class_scope:environmentService.TempRequest)
  })
_sym_db.RegisterMessage(TempRequest)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'environment_pb2'
  # @@protoc_insertion_point(class_scope:environmentService.Empty)
  })
_sym_db.RegisterMessage(Empty)


DESCRIPTOR._options = None

_ENVIRONMENTSERVICE = _descriptor.ServiceDescriptor(
  name='EnvironmentService',
  full_name='environmentService.EnvironmentService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=147,
  serialized_end=339,
  methods=[
  _descriptor.MethodDescriptor(
    name='setRoomTemp',
    full_name='environmentService.EnvironmentService.setRoomTemp',
    index=0,
    containing_service=None,
    input_type=_TEMPREQUEST,
    output_type=_TEMPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getCurrentRoomTemp',
    full_name='environmentService.EnvironmentService.getCurrentRoomTemp',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CURRENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ENVIRONMENTSERVICE)

DESCRIPTOR.services_by_name['EnvironmentService'] = _ENVIRONMENTSERVICE

# @@protoc_insertion_point(module_scope)
