# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: environment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='environment.proto',
  package='environmentService',
  syntax='proto3',
  serialized_options=b'\n\022environmentServiceB\026EnvironmentServiceImplP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x65nvironment.proto\x12\x12\x65nvironmentService\"!\n\x0e\x43urrentRequest\x12\x0f\n\x07\x63urrent\x18\x01 \x01(\x05\"%\n\x0f\x43urrentResponse\x12\x12\n\ncurrentNew\x18\x01 \x01(\t\"\x1b\n\x0bTempRequest\x12\x0c\n\x04temp\x18\x01 \x01(\x05\"\x1f\n\x0cTempResponse\x12\x0f\n\x07tempNew\x18\x01 \x01(\t2\xc9\x01\n\x12\x45nvironmentService\x12_\n\x12getCurrentRoomTemp\x12\".environmentService.CurrentRequest\x1a#.environmentService.CurrentResponse\"\x00\x12R\n\x0bsetRoomTemp\x12\x1f.environmentService.TempRequest\x1a .environmentService.TempResponse\"\x00\x42.\n\x12\x65nvironmentServiceB\x16\x45nvironmentServiceImplP\x01\x62\x06proto3'
)




_CURRENTREQUEST = _descriptor.Descriptor(
  name='CurrentRequest',
  full_name='environmentService.CurrentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current', full_name='environmentService.CurrentRequest.current', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=74,
)


_CURRENTRESPONSE = _descriptor.Descriptor(
  name='CurrentResponse',
  full_name='environmentService.CurrentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='currentNew', full_name='environmentService.CurrentResponse.currentNew', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=113,
)


_TEMPREQUEST = _descriptor.Descriptor(
  name='TempRequest',
  full_name='environmentService.TempRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temp', full_name='environmentService.TempRequest.temp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=142,
)


_TEMPRESPONSE = _descriptor.Descriptor(
  name='TempResponse',
  full_name='environmentService.TempResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tempNew', full_name='environmentService.TempResponse.tempNew', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=175,
)

DESCRIPTOR.message_types_by_name['CurrentRequest'] = _CURRENTREQUEST
DESCRIPTOR.message_types_by_name['CurrentResponse'] = _CURRENTRESPONSE
DESCRIPTOR.message_types_by_name['TempRequest'] = _TEMPREQUEST
DESCRIPTOR.message_types_by_name['TempResponse'] = _TEMPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CurrentRequest = _reflection.GeneratedProtocolMessageType('CurrentRequest', (_message.Message,), {
  'DESCRIPTOR' : _CURRENTREQUEST,
  '__module__' : 'environment_pb2'
  # @@protoc_insertion_point(class_scope:environmentService.CurrentRequest)
  })
_sym_db.RegisterMessage(CurrentRequest)

CurrentResponse = _reflection.GeneratedProtocolMessageType('CurrentResponse', (_message.Message,), {
  'DESCRIPTOR' : _CURRENTRESPONSE,
  '__module__' : 'environment_pb2'
  # @@protoc_insertion_point(class_scope:environmentService.CurrentResponse)
  })
_sym_db.RegisterMessage(CurrentResponse)

TempRequest = _reflection.GeneratedProtocolMessageType('TempRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEMPREQUEST,
  '__module__' : 'environment_pb2'
  # @@protoc_insertion_point(class_scope:environmentService.TempRequest)
  })
_sym_db.RegisterMessage(TempRequest)

TempResponse = _reflection.GeneratedProtocolMessageType('TempResponse', (_message.Message,), {
  'DESCRIPTOR' : _TEMPRESPONSE,
  '__module__' : 'environment_pb2'
  # @@protoc_insertion_point(class_scope:environmentService.TempResponse)
  })
_sym_db.RegisterMessage(TempResponse)


DESCRIPTOR._options = None

_ENVIRONMENTSERVICE = _descriptor.ServiceDescriptor(
  name='EnvironmentService',
  full_name='environmentService.EnvironmentService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=178,
  serialized_end=379,
  methods=[
  _descriptor.MethodDescriptor(
    name='getCurrentRoomTemp',
    full_name='environmentService.EnvironmentService.getCurrentRoomTemp',
    index=0,
    containing_service=None,
    input_type=_CURRENTREQUEST,
    output_type=_CURRENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='setRoomTemp',
    full_name='environmentService.EnvironmentService.setRoomTemp',
    index=1,
    containing_service=None,
    input_type=_TEMPREQUEST,
    output_type=_TEMPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ENVIRONMENTSERVICE)

DESCRIPTOR.services_by_name['EnvironmentService'] = _ENVIRONMENTSERVICE

# @@protoc_insertion_point(module_scope)
