// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: environment.proto

package environmentService;

public final class EnvironmentServiceImpl {
  private EnvironmentServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environmentService_CurrentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environmentService_CurrentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environmentService_CurrentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environmentService_CurrentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environmentService_TempRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environmentService_TempRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environmentService_TempResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environmentService_TempResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021environment.proto\022\022environmentService\"" +
      "!\n\016CurrentRequest\022\017\n\007current\030\001 \001(\005\"%\n\017Cu" +
      "rrentResponse\022\022\n\ncurrentNew\030\001 \001(\t\"\033\n\013Tem" +
      "pRequest\022\014\n\004temp\030\001 \001(\005\"\037\n\014TempResponse\022\017" +
      "\n\007tempNew\030\001 \001(\t2\311\001\n\022EnvironmentService\022_" +
      "\n\022getCurrentRoomTemp\022\".environmentServic" +
      "e.CurrentRequest\032#.environmentService.Cu" +
      "rrentResponse\"\000\022R\n\013setRoomTemp\022\037.environ" +
      "mentService.TempRequest\032 .environmentSer" +
      "vice.TempResponse\"\000B.\n\022environmentServic" +
      "eB\026EnvironmentServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_environmentService_CurrentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_environmentService_CurrentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environmentService_CurrentRequest_descriptor,
        new java.lang.String[] { "Current", });
    internal_static_environmentService_CurrentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_environmentService_CurrentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environmentService_CurrentResponse_descriptor,
        new java.lang.String[] { "CurrentNew", });
    internal_static_environmentService_TempRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_environmentService_TempRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environmentService_TempRequest_descriptor,
        new java.lang.String[] { "Temp", });
    internal_static_environmentService_TempResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_environmentService_TempResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environmentService_TempResponse_descriptor,
        new java.lang.String[] { "TempNew", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
