// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: environment.proto

package environmentService;

public final class EnvironmentServiceImpl {
  private EnvironmentServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environmentService_TempResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environmentService_TempResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environmentService_CurrentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environmentService_CurrentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environmentService_TempRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environmentService_TempRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environmentService_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environmentService_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021environment.proto\022\022environmentService\"" +
      "\036\n\014TempResponse\022\016\n\006result\030\001 \001(\t\" \n\017Curre" +
      "ntResponse\022\r\n\005value\030\001 \001(\005\"\034\n\013TempRequest" +
      "\022\r\n\005value\030\001 \001(\005\"\007\n\005Empty2\300\001\n\022Environment" +
      "Service\022R\n\013setRoomTemp\022\037.environmentServ" +
      "ice.TempRequest\032 .environmentService.Tem" +
      "pResponse\"\000\022V\n\022getCurrentRoomTemp\022\031.envi" +
      "ronmentService.Empty\032#.environmentServic" +
      "e.CurrentResponse\"\000B.\n\022environmentServic" +
      "eB\026EnvironmentServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_environmentService_TempResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_environmentService_TempResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environmentService_TempResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_environmentService_CurrentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_environmentService_CurrentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environmentService_CurrentResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_environmentService_TempRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_environmentService_TempRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environmentService_TempRequest_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_environmentService_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_environmentService_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environmentService_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
