// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: environment.proto

package environmentService;

public interface SetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:environmentService.SetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tempResponse = 1;</code>
   */
  java.lang.String getTempResponse();
  /**
   * <code>string tempResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getTempResponseBytes();
}
