// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: environment.proto

package environmentService;

public interface SetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:environmentService.SetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tempRequest = 1;</code>
   */
  java.lang.String getTempRequest();
  /**
   * <code>string tempRequest = 1;</code>
   */
  com.google.protobuf.ByteString
      getTempRequestBytes();
}
