// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: environment.proto

package environmentService;

public interface TempRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:environmentService.TempRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string temp = 1;</code>
   */
  java.lang.String getTemp();
  /**
   * <code>string temp = 1;</code>
   */
  com.google.protobuf.ByteString
      getTempBytes();
}
