// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: environment.proto

package environmentService;

public interface TempResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:environmentService.TempResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tempNew = 1;</code>
   */
  java.lang.String getTempNew();
  /**
   * <code>string tempNew = 1;</code>
   */
  com.google.protobuf.ByteString
      getTempNewBytes();
}
