// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientAccommodation.proto

package patientAccommodationService;

public interface CalculatetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:patientAccommodationService.CalculatetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 totalPrice = 1;</code>
   */
  int getTotalPrice();
}
