// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientAccommodation.proto

package patientAccommodationService;

public interface CalculateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:patientAccommodationService.CalculateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numberDays = 1;</code>
   */
  int getNumberDays();

  /**
   * <code>.patientAccommodationService.CalculateRequest.Price price = 2;</code>
   */
  int getPriceValue();
  /**
   * <code>.patientAccommodationService.CalculateRequest.Price price = 2;</code>
   */
  patientAccommodationService.CalculateRequest.Price getPrice();
}
