// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientAccommodation.proto

package patientAccommodationService;

public interface DisplayResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:patientAccommodationService.DisplayResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string allPatients = 1;</code>
   */
  java.lang.String getAllPatients();
  /**
   * <code>string allPatients = 1;</code>
   */
  com.google.protobuf.ByteString
      getAllPatientsBytes();
}
