// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientAccommodation.proto

package patientAccommodationService;

public interface RegisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:patientAccommodationService.RegisterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string age = 2;</code>
   */
  java.lang.String getAge();
  /**
   * <code>string age = 2;</code>
   */
  com.google.protobuf.ByteString
      getAgeBytes();

  /**
   * <code>string gender = 3;</code>
   */
  java.lang.String getGender();
  /**
   * <code>string gender = 3;</code>
   */
  com.google.protobuf.ByteString
      getGenderBytes();
}
