// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientMonitoring.proto

package patientMonitoringService;

public interface CalculatetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:patientMonitoringService.CalculatetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 totalPrice = 1;</code>
   */
  int getTotalPrice();
}
