// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientMonitoring.proto

package patientMonitoringService;

public interface CalculateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:patientMonitoringService.CalculateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numberDays = 1;</code>
   */
  int getNumberDays();

  /**
   * <code>int32 priceDay = 2;</code>
   */
  int getPriceDay();
}
