// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patient_monitoring.proto

package patientMonitoringService;

public interface DeviceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:patientMonitoringService.DeviceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
