// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patient_monitoring.proto

package patientMonitoringService;

public interface DeviceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:patientMonitoringService.DeviceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool deviceStatus = 1;</code>
   */
  boolean getDeviceStatus();
}
