// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patient_monitoring.proto

package patientMonitoringService;

public final class PatientMonitoringServiceImpl {
  private PatientMonitoringServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_patientMonitoringService_DeviceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_patientMonitoringService_DeviceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_patientMonitoringService_DeviceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_patientMonitoringService_DeviceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_patientMonitoringService_PressureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_patientMonitoringService_PressureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_patientMonitoringService_PressureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_patientMonitoringService_PressureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030patient_monitoring.proto\022\030patientMonit" +
      "oringService\"%\n\rDeviceRequest\022\024\n\014deviceS" +
      "tatus\030\001 \001(\010\"&\n\016DeviceResponse\022\024\n\014deviceS" +
      "tatus\030\001 \001(\010\"6\n\017PressureRequest\022\020\n\010systol" +
      "ic\030\001 \001(\002\022\021\n\tdiastolic\030\002 \001(\002\"\"\n\020PressureR" +
      "esponse\022\016\n\006result\030\001 \001(\t2\366\001\n\030PatientMonit" +
      "oringService\022l\n\025monitoringDeviceOnOff\022\'." +
      "patientMonitoringService.DeviceRequest\032(" +
      ".patientMonitoringService.DeviceResponse" +
      "\"\000\022l\n\rbloodPressure\022).patientMonitoringS" +
      "ervice.PressureRequest\032*.patientMonitori" +
      "ngService.PressureResponse\"\000(\0010\001B:\n\030pati" +
      "entMonitoringServiceB\034PatientMonitoringS" +
      "erviceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_patientMonitoringService_DeviceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_patientMonitoringService_DeviceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_patientMonitoringService_DeviceRequest_descriptor,
        new java.lang.String[] { "DeviceStatus", });
    internal_static_patientMonitoringService_DeviceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_patientMonitoringService_DeviceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_patientMonitoringService_DeviceResponse_descriptor,
        new java.lang.String[] { "DeviceStatus", });
    internal_static_patientMonitoringService_PressureRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_patientMonitoringService_PressureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_patientMonitoringService_PressureRequest_descriptor,
        new java.lang.String[] { "Systolic", "Diastolic", });
    internal_static_patientMonitoringService_PressureResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_patientMonitoringService_PressureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_patientMonitoringService_PressureResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
