// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patient_monitoring.proto

package patientMonitoringService;

public interface PressureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:patientMonitoringService.PressureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float systolic = 1;</code>
   */
  float getSystolic();

  /**
   * <code>float diastolic = 2;</code>
   */
  float getDiastolic();
}
