// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patient_monitoring.proto

package patientMonitoringService;

public interface PressureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:patientMonitoringService.PressureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
