// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patient_administration.proto

package patientAdministrationService;

public interface CalculateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatientAdministrationService.CalculateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patName = 1;</code>
   */
  java.lang.String getPatName();
  /**
   * <code>string patName = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatNameBytes();

  /**
   * <code>int32 numberDays = 2;</code>
   */
  int getNumberDays();

  /**
   * <code>.PatientAdministrationService.CalculateRequest.Room room = 3;</code>
   */
  int getRoomValue();
  /**
   * <code>.PatientAdministrationService.CalculateRequest.Room room = 3;</code>
   */
  patientAdministrationService.CalculateRequest.Room getRoom();
}
