// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patient_administration.proto

package patientAdministrationService;

public interface CalculateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatientAdministrationService.CalculateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numberDays = 1;</code>
   */
  int getNumberDays();

  /**
   * <code>.PatientAdministrationService.CalculateRequest.Price price = 2;</code>
   */
  int getPriceValue();
  /**
   * <code>.PatientAdministrationService.CalculateRequest.Price price = 2;</code>
   */
  patientAdministrationService.CalculateRequest.Price getPrice();
}
