// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patient_administration.proto

package patientAdministrationService;

public interface CalculatetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatientAdministrationService.CalculatetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 totalPrice = 1;</code>
   */
  int getTotalPrice();
}
