// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patient_administration.proto

package patientAdministrationService;

/**
 * <pre>
 *Unary Call 
 * </pre>
 *
 * Protobuf type {@code PatientAdministrationService.CalculateRequest}
 */
public  final class CalculateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PatientAdministrationService.CalculateRequest)
    CalculateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CalculateRequest.newBuilder() to construct.
  private CalculateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CalculateRequest() {
    patName_ = "";
    numberDays_ = 0;
    room_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CalculateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            patName_ = s;
            break;
          }
          case 16: {

            numberDays_ = input.readInt32();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            room_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return patientAdministrationService.PatientAdministrationServiceImpl.internal_static_PatientAdministrationService_CalculateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return patientAdministrationService.PatientAdministrationServiceImpl.internal_static_PatientAdministrationService_CalculateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            patientAdministrationService.CalculateRequest.class, patientAdministrationService.CalculateRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code PatientAdministrationService.CalculateRequest.Room}
   */
  public enum Room
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PUBLIC = 0;</code>
     */
    PUBLIC(0),
    /**
     * <code>SEMIPRIVATE = 1;</code>
     */
    SEMIPRIVATE(1),
    /**
     * <code>PRIVATE = 2;</code>
     */
    PRIVATE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PUBLIC = 0;</code>
     */
    public static final int PUBLIC_VALUE = 0;
    /**
     * <code>SEMIPRIVATE = 1;</code>
     */
    public static final int SEMIPRIVATE_VALUE = 1;
    /**
     * <code>PRIVATE = 2;</code>
     */
    public static final int PRIVATE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Room valueOf(int value) {
      return forNumber(value);
    }

    public static Room forNumber(int value) {
      switch (value) {
        case 0: return PUBLIC;
        case 1: return SEMIPRIVATE;
        case 2: return PRIVATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Room>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Room> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Room>() {
            public Room findValueByNumber(int number) {
              return Room.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return patientAdministrationService.CalculateRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final Room[] VALUES = values();

    public static Room valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Room(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PatientAdministrationService.CalculateRequest.Room)
  }

  public static final int PATNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object patName_;
  /**
   * <code>string patName = 1;</code>
   */
  public java.lang.String getPatName() {
    java.lang.Object ref = patName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      patName_ = s;
      return s;
    }
  }
  /**
   * <code>string patName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPatNameBytes() {
    java.lang.Object ref = patName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      patName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUMBERDAYS_FIELD_NUMBER = 2;
  private int numberDays_;
  /**
   * <code>int32 numberDays = 2;</code>
   */
  public int getNumberDays() {
    return numberDays_;
  }

  public static final int ROOM_FIELD_NUMBER = 3;
  private int room_;
  /**
   * <code>.PatientAdministrationService.CalculateRequest.Room room = 3;</code>
   */
  public int getRoomValue() {
    return room_;
  }
  /**
   * <code>.PatientAdministrationService.CalculateRequest.Room room = 3;</code>
   */
  public patientAdministrationService.CalculateRequest.Room getRoom() {
    @SuppressWarnings("deprecation")
    patientAdministrationService.CalculateRequest.Room result = patientAdministrationService.CalculateRequest.Room.valueOf(room_);
    return result == null ? patientAdministrationService.CalculateRequest.Room.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPatNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, patName_);
    }
    if (numberDays_ != 0) {
      output.writeInt32(2, numberDays_);
    }
    if (room_ != patientAdministrationService.CalculateRequest.Room.PUBLIC.getNumber()) {
      output.writeEnum(3, room_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPatNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, patName_);
    }
    if (numberDays_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, numberDays_);
    }
    if (room_ != patientAdministrationService.CalculateRequest.Room.PUBLIC.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, room_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof patientAdministrationService.CalculateRequest)) {
      return super.equals(obj);
    }
    patientAdministrationService.CalculateRequest other = (patientAdministrationService.CalculateRequest) obj;

    boolean result = true;
    result = result && getPatName()
        .equals(other.getPatName());
    result = result && (getNumberDays()
        == other.getNumberDays());
    result = result && room_ == other.room_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PATNAME_FIELD_NUMBER;
    hash = (53 * hash) + getPatName().hashCode();
    hash = (37 * hash) + NUMBERDAYS_FIELD_NUMBER;
    hash = (53 * hash) + getNumberDays();
    hash = (37 * hash) + ROOM_FIELD_NUMBER;
    hash = (53 * hash) + room_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static patientAdministrationService.CalculateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static patientAdministrationService.CalculateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static patientAdministrationService.CalculateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static patientAdministrationService.CalculateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static patientAdministrationService.CalculateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static patientAdministrationService.CalculateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static patientAdministrationService.CalculateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static patientAdministrationService.CalculateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static patientAdministrationService.CalculateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static patientAdministrationService.CalculateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static patientAdministrationService.CalculateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static patientAdministrationService.CalculateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(patientAdministrationService.CalculateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Unary Call 
   * </pre>
   *
   * Protobuf type {@code PatientAdministrationService.CalculateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PatientAdministrationService.CalculateRequest)
      patientAdministrationService.CalculateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return patientAdministrationService.PatientAdministrationServiceImpl.internal_static_PatientAdministrationService_CalculateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return patientAdministrationService.PatientAdministrationServiceImpl.internal_static_PatientAdministrationService_CalculateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              patientAdministrationService.CalculateRequest.class, patientAdministrationService.CalculateRequest.Builder.class);
    }

    // Construct using patientAdministrationService.CalculateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      patName_ = "";

      numberDays_ = 0;

      room_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return patientAdministrationService.PatientAdministrationServiceImpl.internal_static_PatientAdministrationService_CalculateRequest_descriptor;
    }

    @java.lang.Override
    public patientAdministrationService.CalculateRequest getDefaultInstanceForType() {
      return patientAdministrationService.CalculateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public patientAdministrationService.CalculateRequest build() {
      patientAdministrationService.CalculateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public patientAdministrationService.CalculateRequest buildPartial() {
      patientAdministrationService.CalculateRequest result = new patientAdministrationService.CalculateRequest(this);
      result.patName_ = patName_;
      result.numberDays_ = numberDays_;
      result.room_ = room_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof patientAdministrationService.CalculateRequest) {
        return mergeFrom((patientAdministrationService.CalculateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(patientAdministrationService.CalculateRequest other) {
      if (other == patientAdministrationService.CalculateRequest.getDefaultInstance()) return this;
      if (!other.getPatName().isEmpty()) {
        patName_ = other.patName_;
        onChanged();
      }
      if (other.getNumberDays() != 0) {
        setNumberDays(other.getNumberDays());
      }
      if (other.room_ != 0) {
        setRoomValue(other.getRoomValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      patientAdministrationService.CalculateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (patientAdministrationService.CalculateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object patName_ = "";
    /**
     * <code>string patName = 1;</code>
     */
    public java.lang.String getPatName() {
      java.lang.Object ref = patName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string patName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPatNameBytes() {
      java.lang.Object ref = patName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string patName = 1;</code>
     */
    public Builder setPatName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      patName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string patName = 1;</code>
     */
    public Builder clearPatName() {
      
      patName_ = getDefaultInstance().getPatName();
      onChanged();
      return this;
    }
    /**
     * <code>string patName = 1;</code>
     */
    public Builder setPatNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      patName_ = value;
      onChanged();
      return this;
    }

    private int numberDays_ ;
    /**
     * <code>int32 numberDays = 2;</code>
     */
    public int getNumberDays() {
      return numberDays_;
    }
    /**
     * <code>int32 numberDays = 2;</code>
     */
    public Builder setNumberDays(int value) {
      
      numberDays_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numberDays = 2;</code>
     */
    public Builder clearNumberDays() {
      
      numberDays_ = 0;
      onChanged();
      return this;
    }

    private int room_ = 0;
    /**
     * <code>.PatientAdministrationService.CalculateRequest.Room room = 3;</code>
     */
    public int getRoomValue() {
      return room_;
    }
    /**
     * <code>.PatientAdministrationService.CalculateRequest.Room room = 3;</code>
     */
    public Builder setRoomValue(int value) {
      room_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.PatientAdministrationService.CalculateRequest.Room room = 3;</code>
     */
    public patientAdministrationService.CalculateRequest.Room getRoom() {
      @SuppressWarnings("deprecation")
      patientAdministrationService.CalculateRequest.Room result = patientAdministrationService.CalculateRequest.Room.valueOf(room_);
      return result == null ? patientAdministrationService.CalculateRequest.Room.UNRECOGNIZED : result;
    }
    /**
     * <code>.PatientAdministrationService.CalculateRequest.Room room = 3;</code>
     */
    public Builder setRoom(patientAdministrationService.CalculateRequest.Room value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      room_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.PatientAdministrationService.CalculateRequest.Room room = 3;</code>
     */
    public Builder clearRoom() {
      
      room_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PatientAdministrationService.CalculateRequest)
  }

  // @@protoc_insertion_point(class_scope:PatientAdministrationService.CalculateRequest)
  private static final patientAdministrationService.CalculateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new patientAdministrationService.CalculateRequest();
  }

  public static patientAdministrationService.CalculateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CalculateRequest>
      PARSER = new com.google.protobuf.AbstractParser<CalculateRequest>() {
    @java.lang.Override
    public CalculateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CalculateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CalculateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CalculateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public patientAdministrationService.CalculateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

