// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patient_administration.proto

package patientAdministrationService;

public interface CalculateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatientAdministrationService.CalculateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
