// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patient_administration.proto

package patientAdministrationService;

public interface DisplayRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatientAdministrationService.DisplayRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patList = 1;</code>
   */
  java.lang.String getPatList();
  /**
   * <code>string patList = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatListBytes();
}
