// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patient_administration.proto

package patientAdministrationService;

public final class PatientAdministrationServiceImpl {
  private PatientAdministrationServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientAdministrationService_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientAdministrationService_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientAdministrationService_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientAdministrationService_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientAdministrationService_DisplayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientAdministrationService_DisplayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientAdministrationService_DisplayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientAdministrationService_DisplayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientAdministrationService_CalculateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientAdministrationService_CalculateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientAdministrationService_CalculateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientAdministrationService_CalculateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034patient_administration.proto\022\034PatientA" +
      "dministrationService\"<\n\017RegisterRequest\022" +
      "\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\t\022\016\n\006gender\030\003 \001" +
      "(\t\"\"\n\020RegisterResponse\022\016\n\006result\030\001 \001(\t\"!" +
      "\n\016DisplayRequest\022\017\n\007patList\030\001 \001(\t\"&\n\017Dis" +
      "playResponse\022\023\n\013allPatients\030\001 \001(\t\"\270\001\n\020Ca" +
      "lculateRequest\022\017\n\007patName\030\001 \001(\t\022\022\n\nnumbe" +
      "rDays\030\002 \001(\005\022I\n\010roomType\030\003 \001(\01627.PatientA" +
      "dministrationService.CalculateRequest.Ro" +
      "omType\"4\n\010RoomType\022\n\n\006PUBLIC\020\000\022\017\n\013SEMIPR" +
      "IVATE\020\001\022\013\n\007PRIVATE\020\002\"$\n\021CalculateRespons" +
      "e\022\017\n\007message\030\002 \001(\t2\375\002\n\034PatientAdministra" +
      "tionService\022t\n\017registerPatient\022-.Patient" +
      "AdministrationService.RegisterRequest\032.." +
      "PatientAdministrationService.RegisterRes" +
      "ponse\"\000(\001\022r\n\017displayPatients\022,.PatientAd" +
      "ministrationService.DisplayRequest\032-.Pat" +
      "ientAdministrationService.DisplayRespons" +
      "e\"\0000\001\022s\n\016calculatePrice\022..PatientAdminis" +
      "trationService.CalculateRequest\032/.Patien" +
      "tAdministrationService.CalculateResponse" +
      "\"\000BB\n\034patientAdministrationServiceB Pati" +
      "entAdministrationServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PatientAdministrationService_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PatientAdministrationService_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientAdministrationService_RegisterRequest_descriptor,
        new java.lang.String[] { "Name", "Age", "Gender", });
    internal_static_PatientAdministrationService_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PatientAdministrationService_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientAdministrationService_RegisterResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_PatientAdministrationService_DisplayRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PatientAdministrationService_DisplayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientAdministrationService_DisplayRequest_descriptor,
        new java.lang.String[] { "PatList", });
    internal_static_PatientAdministrationService_DisplayResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PatientAdministrationService_DisplayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientAdministrationService_DisplayResponse_descriptor,
        new java.lang.String[] { "AllPatients", });
    internal_static_PatientAdministrationService_CalculateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PatientAdministrationService_CalculateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientAdministrationService_CalculateRequest_descriptor,
        new java.lang.String[] { "PatName", "NumberDays", "RoomType", });
    internal_static_PatientAdministrationService_CalculateResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_PatientAdministrationService_CalculateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientAdministrationService_CalculateResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
