// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patient_administration.proto

package patientAdministrationService;

public final class PatientAdministrationServiceImpl {
  private PatientAdministrationServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientAdministrationService_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientAdministrationService_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientAdministrationService_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientAdministrationService_RegisterResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034patient_administration.proto\022\034PatientA" +
      "dministrationService\"<\n\017RegisterRequest\022" +
      "\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\t\022\016\n\006gender\030\003 \001" +
      "(\t\"\"\n\020RegisterResponse\022\016\n\006result\030\001 \001(\t2\224" +
      "\001\n\034PatientAdministrationService\022t\n\017regis" +
      "terPatient\022-.PatientAdministrationServic" +
      "e.RegisterRequest\032..PatientAdministratio" +
      "nService.RegisterResponse\"\000(\001BB\n\034patient" +
      "AdministrationServiceB PatientAdministra" +
      "tionServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PatientAdministrationService_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PatientAdministrationService_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientAdministrationService_RegisterRequest_descriptor,
        new java.lang.String[] { "Name", "Age", "Gender", });
    internal_static_PatientAdministrationService_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PatientAdministrationService_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientAdministrationService_RegisterResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
