// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patient_administration.proto

package patientAdministrationService;

public interface RegisterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatientAdministrationService.RegisterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
