// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientMonitoring.proto

package patientMonitoring;

public interface DeviceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:patientMonitoring.DeviceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool deviceStatus = 1;</code>
   */
  boolean getDeviceStatus();
}
