// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientMonitoring.proto

package patientMonitoring;

public final class PatientMonitoringServiceImpl {
  private PatientMonitoringServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_patientMonitoring_DeviceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_patientMonitoring_DeviceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_patientMonitoring_DeviceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_patientMonitoring_DeviceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_patientMonitoring_PressureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_patientMonitoring_PressureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_patientMonitoring_PressureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_patientMonitoring_PressureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027patientMonitoring.proto\022\021patientMonito" +
      "ring\"%\n\rDeviceRequest\022\024\n\014deviceStatus\030\001 " +
      "\001(\010\"&\n\016DeviceResponse\022\024\n\014deviceStatus\030\001 " +
      "\001(\010\"6\n\017PressureRequest\022\020\n\010systolic\030\001 \001(\002" +
      "\022\021\n\tdiastolic\030\002 \001(\002\"\"\n\020PressureResponse\022" +
      "\016\n\006result\030\001 \001(\0022\330\001\n\030PatientMonitoringSer" +
      "vice\022\\\n\025monitoringDeviceOnOff\022 .patientM" +
      "onitoring.DeviceRequest\032!.patientMonitor" +
      "ing.DeviceResponse\022^\n\rbloodPressure\022\".pa" +
      "tientMonitoring.PressureRequest\032#.patien" +
      "tMonitoring.PressureResponse\"\000(\0010\001B3\n\021pa" +
      "tientMonitoringB\034PatientMonitoringServic" +
      "eImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_patientMonitoring_DeviceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_patientMonitoring_DeviceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_patientMonitoring_DeviceRequest_descriptor,
        new java.lang.String[] { "DeviceStatus", });
    internal_static_patientMonitoring_DeviceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_patientMonitoring_DeviceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_patientMonitoring_DeviceResponse_descriptor,
        new java.lang.String[] { "DeviceStatus", });
    internal_static_patientMonitoring_PressureRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_patientMonitoring_PressureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_patientMonitoring_PressureRequest_descriptor,
        new java.lang.String[] { "Systolic", "Diastolic", });
    internal_static_patientMonitoring_PressureResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_patientMonitoring_PressureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_patientMonitoring_PressureResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
