// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientMonitoring.proto

package patientMonitoring;

public interface PressureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:patientMonitoring.PressureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float systolic = 1;</code>
   */
  float getSystolic();

  /**
   * <code>float diastolic = 2;</code>
   */
  float getDiastolic();
}
