// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientMonitoring.proto

package patientMonitoring;

public interface PressureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:patientMonitoring.PressureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float result = 1;</code>
   */
  float getResult();
}
